/**
 * A product screenshot at the size it is shown. The full-resolution PNGs in
 * docs/screenshots/share (1–2 MB each) stay the <img> fallback for the deck;
 * browsers pick a small WebP rendition from /screens instead (generated by
 * scripts/screen-thumbs.mjs). The width/height attributes carry the source
 * aspect ratio so the frame reserves its space before the image arrives.
 */
const SCREEN_WIDTH = 1170;
const SCREEN_HEIGHT = 2532;
const RENDITIONS = [320, 640];

export function screenName(src: string): string {
  return src.replace(/^.*\//, "").replace(/\.png$/, "");
}

export default function ScreenPicture({
  src,
  alt,
  sizes,
  eager = false,
}: {
  /** The full-resolution PNG path under /docs/screenshots/share. */
  src: string;
  alt: string;
  /** CSS width the image renders at, for srcset selection. */
  sizes: string;
  /** Above-the-fold hero: load right away at normal priority. */
  eager?: boolean;
}) {
  const name = screenName(src);
  const srcSet = RENDITIONS.map((w) => `/screens/${name}-${w}.webp ${w}w`).join(", ");
  return (
    <picture>
      <source type="image/webp" srcSet={srcSet} sizes={sizes} />
      <img
        src={src}
        alt={alt}
        width={SCREEN_WIDTH}
        height={SCREEN_HEIGHT}
        loading={eager ? undefined : "lazy"}
        decoding="async"
        fetchPriority={eager ? "auto" : "low"}
      />
    </picture>
  );
}
